server:
  port: 0

spring:
  application:
    name: news
  config:
    import: optional:configserver:http://localhost:8888
#  profiles:
#    active: test


# url, куда будет происходить регистрация микросервисов
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

# более короткое отображение логов
logging:
  pattern:
    console: '[%-5level] %d{HH:mm:ss} - %msg%n'

