server:
  port: 8761

spring:
  application:
    name: eserver
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8081/eureka

# отключение лишних логов, т.к. не тут не будем создавать и вызывать микросервисы
logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF

# более короткое отображение логов
  pattern:
    console: '[%-5level] %d{HH:mm:ss} - %msg%n'
